### ISSUE TITLE
[RadAutoCompleteTextView]: Ability to select typed text that is not found in suggestions

### ISSUE THREAD

**Issue by chrum** [NativeScript/nativescript-ui-feedback#1218] opened 2019-08-27 14:58 UTC
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
When typed text that cannot be matched with anything we get stuck with 'No results found'.
Seems like we are forced to choose something from the autocomplete. Is there no way to type something else? I know how to get the raw text out of autocomplete but how to finish editing with custom text and no token selection?

### Which platform(s) does your issue occur on?
iOS for sure, didn't try on android yet

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** ^5.1.0
- **CLI:** 6.0.2
- **Cross-platform modules:** 6.0.1
- **Runtime(s):** 6.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Open application (demo from example will be ok)
2. start typing until you run out of suggestions and 'No items found' appears

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
a possible solution was suggested by Ian MacDonald in this [playground](https://play.nativescript.org/?template=play-ng&id=bm3LUe)

**Comment by tsonevn** [comment] 2019-08-28 04:23
Duplicate of https://github.com/NativeScript/nativescript-ui-feedback/issues/482

**Closed** 2019-08-28 06:26 UTC
