### ISSUE TITLE
RadSideDrawer  iOS bug  

### ISSUE THREAD

**Issue by hitmacreed** [NativeScript/nativescript-ui-feedback#1224] opened 2019-09-02 10:13 UTC
When i run the iOS version RadSideDrawer i have the fallowing bug :
```
JavaScript error:
file:///node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js:211:0 JS ERROR TypeError: undefined is not an object (evaluating '_this.mainContent.layout')
NativeScript caught signal 11.
Native Stack:
1   0x10385a84f sig_handler(int)
2   0x109e26b5d _sigtramp
3   0x432f656d69746e75
4   0x109d6cb4d libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x109d70e4c _Unwind_RaiseException
6   0x1099494aa __cxa_throw
7   0x108360bfa _objc_exception_destructor(void*)
8   0x103815d58 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
9   0x10384db60 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
10  0x1041eedd6 ffi_closure_unix64_inner
11  0x1041ef7fa ffi_closure_unix64
12  0x1094745b4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
13  0x1094741c2 __CFRunLoopDoTimer
14  0x109473a2a __CFRunLoopDoTimers
15  0x10946e0cc __CFRunLoopRun
16  0x10946d4d2 CFRunLoopRunSpecific
17  0x10f28b2fe GSEventRunModal
18  0x10a956fc2 UIApplicationMain
19  0x1041ef63d ffi_call_unix64
20  0x121a38480
```

my html
```
<RadSideDrawer tkExampleTitle tkToggleNavButton class="nav-drawer">
...
</RadSideDrawer>
```

my component

```
  private _mainContentText: string;
  
  constructor(private _changeDetectionRef: ChangeDetectorRef, private routerExtensions: RouterExtensions, private location: Location) {
  }
 
  private drawer: RadSideDrawer;

  get mainContentText() {
        return this._mainContentText;
  }

  set mainContentText(value: string) {
        this._mainContentText = value;
  }

   @ViewChild(RadSideDrawerComponent, { static: false }) drawerComponent: RadSideDrawerComponent;
 
  ngAfterViewInit() {
        this.drawer = this.drawerComponent.sideDrawer;
        this._changeDetectionRef.detectChanges();
        
    }

  ngOnInit() {
  }

  openDrawer() {
    this.drawer.showDrawer();
  }

  onCloseDrawerTap() {
    this.drawer.closeDrawer();
  }
}
```

**Comment by VladimirAmiorkov** [comment] 2019-09-02 11:50
Make sure that you have correctly set the `tkMainContent` inline directive to an element in the html declaration. Example cam be found [here](https://github.com/NativeScript/nativescript-ui-samples-angular/blob/1a0c2aad882aa233531a9fac08e1e19dd624c85d/sidedrawer/app/examples/getting-started/getting-started.component.html#L21-L24).

Side note: the `tkExampleTitle` and `tkToggleNavButton` are custom inline directives that are implemented in the demo app in order to easily showcase the current example title and show a back button. Those are not required and you should not need to copy paste them if you do not want to actually created such directives.

**Comment by VladimirAmiorkov** [comment] 2019-09-02 11:52
Closing the issue as I am not able to reproduce it on our side using this demo application: https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/sidedrawer

if you continue to experience this issue let us know and reopen the issue by providing additional information in the form of a runnable sample project or a [playground](https://play.nativescript.org/) demo app.

**Closed by VladimirAmiorkov** 2019-09-02 11:52 UTC

**Comment by hitmacreed** [comment] 2019-09-02 12:08
@VladimirAmiorkov  cant reproduce this in playground but i edited the post

**Comment by VladimirAmiorkov** [comment] 2019-09-02 12:46
Hi @hitmacreed ,

The RadSideDrawer requires you to place your "Page" content to its mainContent property as states here the RadSideDrawer can have only two child elements.

Please follow this getting started article.: 
https://docs.nativescript.org/angular/ui/professional-ui-components/ng-SideDrawer/getting-started#initialization
