### ISSUE TITLE
[RadListView] How does replacing items object impact RadListView performance?

### ISSUE THREAD

**Issue by taras** [NativeScript/nativescript-ui-feedback#1083] opened 2019-04-15 16:13 UTC
### Tell us about the problem

I'm building component that allows users to interact with data in a list. The data will be changing a lot and even with a small list I'm seeing performance degradation on Android. I started looking at the implementation of RadListView but it's somewhat difficult to read the compiled source code.  From what I can understand, RadListView has special consideration for ObservableArray, but it's not clear how deep that consideration goes. 

Here are the question that I'd love to get answered,

1. What happens to the views when array passed to `items` is replaced?
2. What happens to the views when the ObservableArray passed to `items` is replaced?
3. When an object in ObservableArray changes, do these changes automatically update the view, reusing views for items that were not changed?
4. When an object in Array changes but all except the changed items remain unchanged, does RadListView reuse the views for the unchanged items?

### Which platform(s) does your issue occur on?

This applies to both iOS and Android.

**Comment by taras** [comment] 2019-04-15 18:39
It's worth noting that Vue's documentation for RadListView has the following comment https://docs.nativescript.org/vuejs/ns-ui/ListView/getting-started#using-observablearray which suggests that arrays are not expected to be used for reactive UI.

**Comment by VladimirAmiorkov** [comment] 2019-04-16 15:00
Hi @taras ,

By design the `RadListView` can be used with both simple `Array` and `ObservableArray` where one is better than the other is if changes to the collection are expected at runtime (after an user has scrolled the list for example). In such scenarios using a simple `Array` would cause the RadListView to scroll to its begging while if `ObservableArray` is used the scroll will not be moved but rather the new element will be "injected" it its place or remove depending on the action done to the `ObservableArray`. This is the general idea behind the support for `Array` and `ObservableArray` in `RadListView`.

Let me try to give some input on the questions you have:
1. If you completely replace the bound to the `items` collection the `RadListView` will dispose all of it's currently cashed containers (on the JS part, not the native part) and start its layout mechanism from scratch. 
2. Same as point 1, there is not difference here due to the fact that the entire layout is considered "dirty" and needs to be refresh.
3. This is different between iOS and Android and on what exactly those changes are. So for example a change to a text of a `Label` will be updated and seen on the screen but if that text is bigger and would require the Label itself to change its height/width that change will not be propagated to the View and it will look cutoff.  We are aware of this issue and you can follow it [here](https://github.com/telerik/nativescript-ui-feedback/issues/846).
4. When working with a simple `Array` any change to the array's elements will cause a complete refresh of the RadListView. This is due to the fact that the `Array` itself does not provide any information about changes to its contents unlike `ObservableArray`.

**Comment by taras** [comment] 2019-04-17 11:58
@VladimirAmiorkov thank you for taking the time to answer my questions. 

> By design the RadListView can be used with both simple Array and ObservableArray where one is better than the other is if changes to the collection are expected at runtime.

Is this also the case for ListView? or is ListView strictly designed to be used in cases where the data won't change at runtime?

Does nesting observable objects into ObservableArray have an impact on performance in RadListView?

**Comment by nmandyam** [comment] 2019-06-20 08:32
This is certainly not working the way it is advertised, for me. I have a RadListView in the XML and am setting its items via an OberservableArray. Changes to items in the ObservableArray ( by setItem({...}) ) are not reflected automatically in the UI; they're only shown if I call a refresh() on the RadListView after setting the item. This is identical behaviour to, say, a ListView, so I don't see any value to the RadListView over ListView and Repeater.
Now for my question: if refresh() bad for performance? Is it better to complain here and get RadListView fixed instead of just using refresh() and moving on?

**Comment by VladimirAmiorkov** [comment] 2019-06-20 08:44
Hi @nmandyam ,

I would suggest you to open a new issue and attach a project that clearly shows the issue you are experiencing. Simple complaining and waiting for a fix is not the best approach because we cannot correctly investigate and issue without information like what version of the plugin you are using, what platform you are experiencing the issue (Android, iOS, Angular, Vue etc.), what exactly you are doing and in what specific order. I would recommended you to open a new issue and input all of the required information by going [here](https://github.com/NativeScript/nativescript-ui-feedback/issues/new).

**Comment by VladimirAmiorkov** [comment] 2019-06-20 08:47
@taras 

> Does nesting observable objects into ObservableArray have an impact on performance in RadListView?

We cannot verify this as it is a very general question and it depends on the objects themselves and the frequency on when they are being updated and if and how the changes to those observable objects is reflecting in the UI (are the properties that are being changed on that object supposed to update the UI of the RadListView itemTemplarte etc.)

**Comment by nmandyam** [comment] 2019-06-20 09:30
Good advice, thanks. Can you please answer my question about refresh performance, though?

**Comment by VladimirAmiorkov** [comment] 2019-06-20 12:10
@nmandyam Calling `refresh()` is is basically a complete refresh of the list. This will not cause the performance to be any worst than what you see initially when that list is being loaded, when you call that API two things happen:
1. This list will be reloaded as expected and its scroll will be reset
2. The app will use memory and CPU to re-render all if the list

If you call that API constantly during scrolling and other UX actions this will of course make the app performance go down. The [refresh()](https://docs.nativescript.org/ns-ui-api-reference/classes/radlistview#refresh) method is designed for one purpose, to **refresh/rebuild** the list it is **not designed** to be used as "update" which is causing some misunderstanding when using it.

**Comment by taras** [comment] 2019-06-20 15:18
> @taras
> 
> > Does nesting observable objects into ObservableArray have an impact on performance in RadListView?
> 
> We cannot verify this as it is a very general question and it depends on the objects themselves and the frequency on when they are being updated and if and how the changes to those observable objects is reflecting in the UI (are the properties that are being changed on that object supposed to update the UI of the RadListView `itemTemplate` etc.)

Hi @VladimirAmiorkov, I figured it out. RadListView listens for changes on ObservableArray to know when the list changed and listens for changes on Observable object to know when item properties change. Both ObservableArray and Observable need to keep references stable to prevent RadListView from re-creating corresponding native view instances.

I'm happy to close this issue, my original questions have been answered.

**Comment by VladimirAmiorkov** [comment] 2019-06-20 20:17
@taras Yes exactly. Glad to have helped.

**Closed** 2019-06-20 20:21 UTC
Labels: listview, question

**Comment by gmavritsakis** [comment] 2020-04-28 14:35
What about angular 8 and load on demand ?
I am trying to update specific items (lazy fetch additional data) with no success on IOS.

Having an ObservableArray as data source, trying to setItem on the ObservableArray seems to refresh the full list for each item we update on IOS where on Android it refreshes the items as it should.
What can we do to update some items without refreshing the full list on IOS?

( I have tried wrapping the updates inside suspendUpdates() and resumeUpdates(false) but doing so will not update anything and if I use resumeUpdates(true) it will refresh the list )

**Comment by cjohn001** [comment] 2020-06-01 18:10
Hello, I have the same problem. I tried to set multiple items via push, as I have not found a different way yet to get radlistview (8.2.0) to update its items under IOS. If I set the item bindings to the listview to a new array or observable array, the items are not redrawn correctly.

this._observableArray.push(...tmpArray);
Seems like the view is than update for each inserted item, hence the animations look more than ugly. Hence, no solution either. Have you found a workaround to disable/enable notifications when setting new elements to the observable array?

Note, manual refresh does not work either on IOS for me, i.e.
const listView = this._List.nativeElement as RadListView;
listView.refresh();
