### ISSUE TITLE
Change order of grouping after grouping function in listview

### ISSUE THREAD

**Issue by Willhay108-imprint** [NativeScript/nativescript-ui-feedback#1272] opened 2019-10-17 09:33 UTC
### Tell us about the problem

I have a listview that is being grouped by date. As I cannot manipulate the grouping past the actual grouping function itself it results in the latest date being at the bottom of the page rather than the top. More functionality to manipulate the grouping order after it has been grouped would be fantastic, at the very least being able to reverse the order would also be great.

### Which platform(s) does your issue occur on?
Both

**Comment by tsonevn** [comment] 2019-10-18 06:15
HI @Willhay108-imprint,
Can you provide some more info about your project and the functionality that you want to achieve in your app? Also, it will help if you can create a demo app in [NativeScript Playground](https://play.nativescript.org/), that shows the problem, you are facing.

**Comment by tsonevn** [comment] 2019-10-18 07:25
Hi @Willhay108-imprint,
This issue seems to be a duplicate of https://github.com/NativeScript/nativescript-ui-feedback/issues/1213. I will close this one in favour of #1213.

**Closed by tsonevn** 2019-10-18 07:25 UTC
