### ISSUE TITLE
RadListView custom group sorting with template not working when enableCollapsibleGroups="true" 

### ISSUE THREAD

**Issue by mandar-bhong** [NativeScript/nativescript-ui-feedback#1149] opened 2019-06-05 11:44 UTC
RadListView custom group filter but after use enableCollapsibleGroups="true" that time not work

[here example](https://play.nativescript.org/?template=play-ng&id=KCpViw&v=18)

we have both required grouping collapsible and custom group filter how to solve issue

**Comment by tsonevn** [comment] 2019-06-13 12:21
Duplicate of https://github.com/NativeScript/nativescript-ui-feedback/issues/1102

**Closed by tsonevn** 2019-06-13 12:21 UTC
