### ISSUE TITLE
Border of SuggestionView in RadAutoCompleteTextView

### ISSUE THREAD

**Issue by meysam-mahmoodi** [NativeScript/nativescript-ui-feedback#1159] opened 2019-06-22 12:14 UTC
### Tell us about the problem
I want to add a border style to SuggestionView element in RadAutoCompleteTextView. Now I can add a border to each item of the SuggestionView element but it is not what I want.

![image](https://user-images.githubusercontent.com/39044062/59963759-de1b7b80-950c-11e9-82c7-d6f20fee1456.png)

As I said and you see, want to add a border to the box "No Items Found".

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** `"nativescript-ui-autocomplete": "^3.11.0"`
- **CLI:** 5.4.0
- **Cross-platform modules:** ^6.0.0-next-2019-05-22-144539-02
- **Runtime(s):** "version": ```    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.2"
    }```

**Comment by tsonevn** [comment] 2019-06-24 05:56
Duplicate of https://github.com/NativeScript/nativescript-ui-feedback/issues/1117

**Closed by tsonevn** 2019-06-24 05:56 UTC
Labels: autocomplete
